### ISSUE TITLE
Messenger on non routed messages

### ISSUE THREAD

**Issue by flohw** [zenstruck/messenger-test#41]
Hello,

I just found this library which may feet our needs and usable with your browser and foundry library which we already like :slightly_smiling_face: 

We are using the messenger with async message and also messages which are not routed. Is there a way to handle them with this library? As there is no transport, I have a doubt but we can't route all of our message and most of them must be kept synchronous.

Maybe you can give me an advice on how I can test my message is dispatched by my controller? I didn't find a solution except by using the profiler but it might not be the better solution, isn't it?

Thanks

**Comment by kbond** [comment]
By "non-routed message", I guess you mean the default sync handling?

Right now, you can only test by creating a sync test transport and routing these messages to it:

```yaml
framework:
    messenger:
        transports:
            sync: 'test://?intercept=false'
        routing:
            'App\Message\MyMessage': sync
```

What are you trying to achieve by using this library for these messages? Since these messages are dispatched immediately, can't you test the _effect_ of the dispatch?
