### ISSUE TITLE
Check stamps and final message

### ISSUE THREAD

**Issue by CharloMez** [zenstruck/messenger-test#5]
Is there a way to check stamps and the final message with this library ?
I explain myself.
I use messenger with rabbitmq, and between different microservices.
To perform that, I use a specific stamp to give the routing_key dynamically when i dispatch the message
```
    $envelope = new Envelope(
            $fooMessage,
            [
                new AmqpStamp("myexchange.{$bar}")
            ]
    );
```

And secondly I use symfony serializer to not pair the message with specific class.

```
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
```

and the normalizer:
```
<?php

namespace App\Serializer\Normalizer;

use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class FooNormalizer implements NormalizerInterface
{
    /**
     * @param Envelope $object
     * @param string|null $format
     * @param array $context
     *
     * @return array
     */
    public function normalize($object, string $format = null, array $context = [])
    {
        /** @var FooMessage $fooMessage */
        $fooMessage = $object->getMessage();

        return [
            'body' => [
                'foo' => $fooMessage->bar(),
            ],
            'headers' => [
                'stamps' => $object->all()
            ]
        ];
    }

    public function supportsNormalization($data, string $format = null)
    {
        return $data instanceof Envelope
            && $data->getMessage() instanceof FooMessage
        ;
    }
}
```

I would like to perform fonctional testing on it, and for me it's very important to check that my stamp is good and that my final message too (I mean the final json which will really be in my queue).

I saw that you have the serializer in your transport class, is it possible to provide a function to get the serialized message ?
And I don't know how yet, but do you think it is possible to have a function to verify stamps instance and content ?

I don't have time to watch now, but if it is a good idea for you, i can look at it later and make a PR.

thanks !

**Comment by kbond** [comment]
> but do you think it is possible to have a function to verify stamps instance and content

In your case, would the stamp be available on the envelope?

```php
foreach ($this->messenger()->queue() as $envelope) {
    $envelope->all(); // is the listed stamp here?
}
```

**Comment by CharloMez** [comment]
Just check it, yes this works fine for stamps my bad i didn't see
```
        $stamps = [];
        foreach ($this->transport('foo_transport')->queue() as $envelope) {
            $stamps = $envelope->all();
        }

        $this->assertArrayHasKey(AmqpStamp::class, $stamps);
        $this->assertSame('myexchange.bar_type', $stamps[AmqpStamp::class][0]->getRoutingKey());

```

But it could be more friendly i think.
It would be really great to provide some assert and accessors like for messages:
```
public function assertStampsContains | notContains(string $stampClass)

public function stamps(string $Class)
```

And for the serialized message I thought about a property `serializedMessages` in your `TestTransport.php` 

and in your `EnvelopeCollection.php` a 
```
public function getSerializedMessage(?string $class = null)
```
which get the serialized message which represent the $class message

What do you think about it ?

**Comment by kbond** [comment]
> But it could be more friendly i think.

Absolutely! I'm thinking about how the API for this should work though. I'm trying to think where the `assertStamps(Not)Contains()` assertions should _live_.

> public function getSerializedMessage(?string $class = null)

Still trying to understand this one - you want this method to return the serialized _string_ for the message?

**Comment by kbond** [comment]
Currently, it's difficult to get the exact envelope/message you want if there are multiple messages sent with the same message class. Perhaps #3 could help but instead of returning `Envelope` it returns a wrapped `TestEnvelope` with the stamp assertions on it?

**Comment by CharloMez** [comment]
> > public function getSerializedMessage(?string $class = null)
> 
> Still trying to understand this one - you want this method to return the serialized _string_ for the message?

Yes thats what I want, but serialized by the right serializer, the one I configure in messenger
```
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
```


It's possible to configure a specific serializer per transport like this:
```
external_messages:
    dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
    serializer: App\Messenger\ExternalJsonMessageSerializer
```
Like explain here https://symfonycasts.com/screencast/messenger/transport-serializer

So it's not a complete functionnal test since we can't check the output of these serialisation

**Comment by CharloMez** [comment]
> Absolutely! I'm thinking about how the API for this should work though. I'm trying to think where the `assertStamps(Not)Contains()` assertions should _live_.
> 

Maybe creating a `StampCollection` with these function and in `TestTransport.php` a function
```
    public function stamp(string $queueName): StampCollection
```
I feel we loose the queue name in your lib, but a function like this would be great.  
Like that in test we could do
```
$this->transport('my_transport')->stamp('queue_name')->assertContains(AmqpStamp::class);
```

Would be the mirror of this conf:
```
        transports:
            my_transport:
                dsn: '%env(MESSENGER_DEFAULT_DSN)%'
                options:
                    ...
                    queues:
                        queue_name:
                            binding_keys:
                                ....
```

**Comment by kbond** [comment]
The "queue_name" is an option that not all transports have, isn't it? The `AmqpStamp` is specific to the `AmpqTransport` so it just wouldn't be there when using the test transport.

**Comment by kbond** [comment]
For the stamp assertions, I was thinking these would only be applicable for "user-defined" stamps (ie `DelayStamp`).

**Comment by CharloMez** [comment]
> The "queue_name" is an option that not all transports have, isn't it? The `AmqpStamp` is specific to the `AmpqTransport` so it just wouldn't be there when using the test transport.

hmm yeah right, amqb have specific conf, cf. doc:
```
    messenger:
        transports:
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # queue_name is specific to the doctrine transport
                    queue_name: high

                    # for AMQP send to a separate exchange then queue
                    #exchange:
                    #    name: high
                    #queues:
                    #    messages_high: ~
                    # or redis try "group"
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: low
```

Complicate to handle everything

**Comment by kbond** [comment]
> Just check it, yes this works fine for stamps my bad i didn't see

I'm not seeing how [this](https://github.com/zenstruck/messenger-test/issues/5#issuecomment-818739393) code snipped works? How is the AmpqStamp being added when using this lib's `TestTransport`?

**Comment by CharloMez** [comment]
> For the stamp assertions, I was thinking these would only be applicable for "user-defined" stamps (ie `DelayStamp`).

Mostly yes, but I think not only. Some library/bundles can apply specific stamps based on annotations in the application (I mainly think about api-platform, but I don't have example). In that case, you want to check tier library/bundles stamps to be sure you configure in the right way

**Comment by kbond** [comment]
> I'm not seeing how this code snipped works?

Forget this - I see now you're adding it (it's user defined). I thought it was something the AmpqTransport added....

**Comment by kbond** [comment]
So to summarize my understanding here, I'm seeing two separate features:

1. Easy access to and assertions on envelope stamps. Could an api like this work?
    ```php
    $this->messenger('my_transport')->queue()->first(MyMessage::class)->assertHasStamp(AmpqStamp::class);
    ```
2. Access the raw serialized string for a message. Could an api like this work?
    ```php
    $serializedString = $this->messenger('my_transport')->queue()->first(MyMessage::class)->serialized();
    ```
    I'm still trying to find the value of this one. Are you going to be making assertions on the raw string?

**Comment by kbond** [comment]
> Some library/bundles can apply specific stamps based on annotations in the application

What I meant is we can't make assertions on the stamps different "transports" add.

**Comment by CharloMez** [comment]
> So to summarize my understanding here, I'm seeing two separate features:
> 
> 1. Easy access to and assertions on envelope stamps. Could an api like this work?
>    ```
>    $this->messenger('my_transport')->queue()->first(MyMessage::class)->assertHasStamp(AmpqStamp::class);
>    ```
> 2. Access the raw serialized string for a message. Could an api like this work?
>    ```
>    $serializedString = $this->messenger('my_transport')->queue()->first(MyMessage::class)->serialized();
>    ```
>    
>    
>    I'm still trying to find the value of this one. Are you going to be making assertions on the raw string?

Yes that would be great, but with your other comment I understand that if we configure specific serializer per transport we can't have them threw your transport.

**Comment by kbond** [comment]
Can you not do?

```yaml
# config/packages/test/messenger.yaml

framework:
    messenger:
        transports:
            async:
                dsn: test://
                serializer: App\Messenger\ExternalJsonMessageSerializer
```

The `TestTransportFactory` should create the `TestTransport` with your configured serializer. _Admittedly, this advanced messenger stuff is a little out of my depth._
