### ISSUE TITLE
Multiple transports setup issue

### ISSUE THREAD

**Issue by hristonev** [zenstruck/messenger-test#63]
Hello, I'm trying to set up this library. According to the documentation I have:
```yaml
#config/packages/messenger.yaml

when@test:
    framework:
        messenger:
            transports:
                reporting: test://
```
```php
#tests/Api/StatementTest.php

use Zenstruck\Messenger\Test\InteractsWithMessenger;

class StatementTest extends BaseWebTestCase
{
    use InteractsWithMessenger;

    #[TestDox('$name')]
    #[DataProvider('statementProvider')]
    public function testCRUD(string $name, array $request, array $responseExpected)
    {
        $this->transport('reporting')->queue();
...
```
Seems that Bundle can't read yaml-configuration because of the error:
```bash
✘ Check·report·message·was·sent
   ┐
   ├ LogicException: Transport "reporting" needs to be set to "test://" in your test config to use this feature.
   │
   │ /var/www/html/vendor/zenstruck/messenger-test/src/Transport/TestTransportRegistry.php:50
   │ /var/www/html/vendor/zenstruck/messenger-test/src/InteractsWithMessenger.php:90
   │ /var/www/html/tests/Api/StatementTest.php:37
```
I have multiple messenger transports.
Please help with any suggestions. Thanks in advance.
