### ISSUE TITLE
transport options are not processed when configure in the options

### ISSUE THREAD

**Issue by aegypius** [zenstruck/messenger-test#79]
In the factory, the options array is ignored so it's not possible to use it to specify options instead of in the dsn. 

For example: 

```yaml 
my_queue:
  dsn: 'test://'
     options:
        queue_name: low
        disable_retries: false
``` 

or 

```php 
$messengerConfig->transport('my_queue')
  ->dsn('test://')
    ->options([
       'queue_name' => 'low', 
       'disabled_retries' => false,
    ])
```

Is there any possible problem to merge options with the parsed options from dsn to allow to use the array syntax ? 

I am willing to make a pull-request, if you think it's pertinent. 

Thanks !
